// FETCH API movies
export const FETCH_API_MOVIES_INITIATED = "FETCH_API_MOVIES_INITIATED";
export const FETCH_API_MOVIES_FAILED = "FETCH_API_MOVIES_FAILED";
export const FETCH_API_MOVIES_EMPTY = "FETCH_API_MOVIES_EMPTY";
export const FETCH_API_MOVIES_SUCCEEDED = "FETCH_API_MOVIES_SUCCEEDED";

// FETCH API movie
export const FETCH_API_MOVIE_INITIATED = "FETCH_API_MOVIE_INITIATED";
export const FETCH_API_MOVIE_FAILED = "FETCH_API_MOVIE_FAILED";
export const FETCH_API_MOVIE_SUCCEEDED = "FETCH_API_MOVIE_SUCCEEDED";

// CREATE API movie
export const CREATE_API_MOVIE_INITIATED = "CREATE_API_MOVIE_INITIATED";
export const CREATE_API_MOVIE_SUCCEEDED = "CREATE_API_MOVIE_SUCEEDED";
export const CREATE_API_MOVIE_FAILED = "CREATE_API_MOVIE_FAILED";
// UPDATE API movie
export const UPDATE_API_MOVIE_INITIATED = "UPDATE_API_MOVIE_INITIATED";
export const UPDATE_API_MOVIE_SUCCEEDED = "UPDATE_API_MOVIE_SUCEEDED";
export const UPDATE_API_MOVIE_FAILED = "UPDATE_API_MOVIE_FAILED";
// DELETE API movie
export const DELETE_API_MOVIE_INITIATED = "DELETE_API_MOVIE_INITIATED";
export const DELETE_API_MOVIE_SUCCEEDED = "DELETE_API_MOVIE_SUCEEDED";
export const DELETE_API_MOVIE_FAILED = "DELETE_API_MOVIE_FAILED";

// OTHERS
export const MOVIE_CLICKED = "MOVIE_CLICKED";
